переход на Serialization + правки по коду
MaxFix/LearnEnglishWordsTelegramBot pull request #10
Opened 2023-08-18 09:35 UTC by MaxFix

2023-08-18 12:02 UTC, danelyan requested changes

2023-08-18 12:02 UTC, danelyan commented on src/main/kotlin/Telegram.kt
>      val botService = TelegramBotService(botToken)
Не сразу обратил внимание. Токен должен передаваться через аргументы main()
Еще иногда "переменные окружения" для этого используют.
Это важно, чтобы в репозитории не святить секреты.

Верни как было )

2023-08-18 12:02 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +fun checkNextQuestionAndSend(json: Json, trainer: WordsTrainer, botToken: String, chatId: Long) {
Перенеси этот метод внутрь TelegramBotService

2023-08-18 12:02 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +    fun getUpdates(botToken: String, updateId: Long): String {
У тебя же токен есть в TelegramBotService, зачем передавать его?

2023-08-18 12:02 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +    fun sendMessage(json: Json, botToken: String, chatId: Long, message: String): String {
тут botToken не нужен, `json: Json` также можно унести в val для TelegramBotService

2023-08-18 16:34 UTC, danelyan requested changes

2023-08-18 16:34 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        val updates = response.result
ненужная строка

2023-08-18 16:34 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    val botService = TelegramBotService(botToken,json)
Метод `handleUpdate(...)` ты вызываешь часто, так как он находится в цикле. Поэтому нужно быть внимательнее к тому, что создается внутри метода.

TelegramBotService явно не нужно создавать каждый раз. Создай его один раз до цикла и прокидывай в этот метод вместо json и botToken

2023-08-18 16:34 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    val statistics = trainer.getStatistics()
зачем тут получать статистику? да, сейчас это легковесная функция и можно позволить себе вызывать ее каждый вызов handleUpdate, но вдруг в будущем ты решишь хранить результаты в базе или на на другом сервере?
Давай подсчет статистики перенесем ближе к месту где она используется

2023-08-18 16:34 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        TelegramBotService(botToken,json).checkNextQuestionAndSend(trainer, chatId)
у тебя же уже есть botService, зачем создавать?

2023-08-18 16:34 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +    fun getUpdates(updateId: Long): String {
переменная updateId не очень точно называется, скорее lastUpdateId, так будет понятнее другим разработчикам, читающим твой код

2023-08-18 16:34 UTC, danelyan commented on src/main/kotlin/WordsTrainer.kt
> +    private val fileName: String = "words.txt",
а попробуй сделать fileName просто параметром конструктора
```Kotlin
class WordsTrainer(
    fileName: String = "words.txt",
   // ...
}
```

Найдешь ошибку в loadDictionary()

2023-08-19 18:08 UTC, danelyan requested changes

2023-08-19 18:08 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        val responseString: String = TelegramBotService(botToken, json).getUpdates(lastUpdateId)
Зачем создавать каждый раз новый TelegramBotService?

> 
> Метод handleUpdate(...) ты вызываешь часто, так как он находится в цикле. Поэтому нужно быть внимательнее к тому, что создается внутри метода.
> 
> TelegramBotService явно не нужно создавать каждый раз. Создай его один раз до цикла и прокидывай в этот метод вместо json и botToken
> 
>

2023-08-19 18:08 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        val botService = TelegramBotService(botToken, json)
до цикла

2023-08-20 08:31 UTC, MaxFix commented
Мне не нравится то, что слова unlearnedWords.take(numberOfSelectedWords) берутся первые 4, а не рандомно из всего списка..

2023-08-20 10:19 UTC, danelyan requested changes
Обрати внимание на то, как ты выбираешь слова методом take(). Надо сначала перемешать, а потом делать take

2023-08-20 10:19 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +            trainer.createAndGetNextQuestion()?.let { sendQuestionToUser(chatId, it) }
тут баг )

2023-08-20 10:19 UTC, danelyan commented on src/main/kotlin/WordsTrainer.kt
> +        dictionary.forEach{ it.learned = 0}
форматирование (пробел перед скобкой)

2023-08-20 10:22 UTC, MaxFix commented on src/main/kotlin/TelegramBotService.kt
> +            trainer.createAndGetNextQuestion()?.let { sendQuestionToUser(chatId, it) }
Не видеть)

2023-08-20 10:23 UTC, MaxFix commented on src/main/kotlin/TelegramBotService.kt
> +            trainer.createAndGetNextQuestion()?.let { sendQuestionToUser(chatId, it) }
Тоже связанный с форматированием?

2023-08-20 10:27 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +            trainer.createAndGetNextQuestion()?.let { sendQuestionToUser(chatId, it) }
тебе нужно тут делать два раза createAndGetNextQuestion()? ты же даже метод переименовал для наглядности

2023-08-20 10:52 UTC, MaxFix commented
Исправил форматирование, сначала делаю перемешивание слов в словаре, а затем выбираю + не делаю лишний вызов createAndGetNextQuestion

2023-08-20 11:39 UTC, danelyan requested changes

2023-08-20 11:39 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        if(question?.variants != null) {
тут достаточно сам question проверять на null

2023-08-20 11:39 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        if(question?.variants != null) {
и не собирается проект (

2023-08-20 19:57 UTC, danelyan approved these changes
![254493805-90d51a89-90c9-4844-924e-da06091a1177](https://github.com/MaxFix/LearnEnglishWordsTelegramBot/assets/7125622/585809aa-2170-43c9-bc07-8b7d5dd8659a)

Поздравляю! Ты сделал бота на Kotlin.
Основная часть работы пройдена.

Теперь этот бот твой - можешь развивать его как хочешь.
Дальше мы обычно предлагаем идеи по развитию, к примеру:

- Добавить возможность показывать картинку в качестве подсказки к изучаемому слову (можно даже делать ее заблюреной - такая фича в телеграме)
- Загрузка своего словаря. Ты нажимаешь кнопку "Добавить слова", бот запрашивает файл. Отправляешь - и словарь пополняется (это кстати дополняет твою доработку)
- Сделать чтобы новый вопрос заменял старый, таким образом чат станет чище
- Написать unit-тесты на бизнес-логику бота

В целом - можем сделать все доработки, при желании 😅

Так как у тебя уже есть своя идея, сейчас набросаю варианты решения в личку )

2023-08-21 00:17 UTC, merged