LearnEnglishWordsTelegramBot Этап 5
MaxFix/LearnEnglishWordsTelegramBot pull request #5
Opened 2023-08-04 20:05 UTC by MaxFix

Сделал функциональность по сравнению значения ответа и записи в файл, но пока что значение в файле затирается первым ответом в серии..

2023-08-04 20:09 UTC, MaxFix commented
Пока не добавил пункт с "0" для возврата

2023-08-07 07:29 UTC, ievetrov requested changes
Отлично! Общая логика верна, но давай немного оптимизируем

2023-08-07 07:29 UTC, ievetrov commented on src/main/kotlin/Main.kt
> +        val wordsFile1 = File("some_words.txt")
а для чего в имени файлов индекс 1?

2023-08-07 07:29 UTC, ievetrov commented on src/main/kotlin/Main.kt
> +    fun saveDictionary(mutableList: MutableList<Word>) {
имя переменной mutableList стандартное, поменяй на более подходящее

2023-08-07 07:29 UTC, ievetrov commented on src/main/kotlin/Main.kt
> +                    var learnedWords = dictionary.filter { it.learned >= 3 }
давай вынесем числа 3 и 4 в константы с нормальными именами, иначе не совсем понятно по коду, что они из себя представляют. Более того - если придется менять это значение, высок риск забыть его поменять в одном месте.
Кстати, в статистических анализаторах это называется MagicNumber

2023-08-07 07:29 UTC, ievetrov commented on src/main/kotlin/Main.kt
> +                        val selectedWord = dictionary.find { it.original == unlearnedWord }
allWords у тебя уже хранит экземпляры нужных слов, ведь когда ты делал filter на словарь, сущности фактически не копировались, операции проводились только с ссылками на них.
Поэтому ты можешь просто обратиться по индексу в список allWords, поменять у найденного слова значение и сделать saveDictionary(...)

2023-08-07 07:36 UTC, MaxFix commented on src/main/kotlin/Main.kt
> +        val wordsFile1 = File("some_words.txt")
без индекса Name shadowed: wordsFile

2023-08-07 07:55 UTC, MaxFix commented on src/main/kotlin/Main.kt
> +                    var learnedWords = dictionary.filter { it.learned >= 3 }
да, понял )
Магическими называют такие числа в коде, смысл которых понятен только написавшему их программисту

2023-08-07 07:59 UTC, danelyan approved these changes
Да, теперь все хорошо. Двигаемся дальше )

2023-08-07 07:59 UTC, merged