EnglishTelegramBot, Этап 9
MaxFix/LearnEnglishWordsTelegramBot pull request #9
Opened 2023-08-16 15:37 UTC by MaxFix

2023-08-16 15:41 UTC, MaxFix commented
1) бот не работает корректно, поэтому есть вопрос
не до конца понял как правильно реализовать отправку вариантов в "inline_keyboard", сейчас бот присылает загаданное слово, без вариантов ответа

2023-08-16 20:53 UTC, danelyan requested changes

2023-08-16 20:53 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +            data = matchResultData.groupValues[1]
Вместо использования if, можно задействовать безопасный вызов ([safe call](https://kotlinlang.org/docs/null-safety.html#safe-calls)):
```Kotlin
data =  matchResultData?.groupValues?.getOrNull(0)
```
Причем data в данном случае не делал бы пробелом, тут тот случай когда null уместен - он говорит нам, что в апдейтах не было поля data. Ведь гипотетически оно могло быть со значением "".

ps:

Ниже тебе пригодится:
```Kotlin
data?.startsWith(CALLBACK_DATA_ANSWER_PREFIX) == true
```

2023-08-16 20:53 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        if (matchResultData != null && matchResultData.groupValues[1] == STATISTICS_TEXT.lowercase()) {
У тебя же уже есть переменная data, зачем снова делать `matchResultData.groupValues[1]` ?

2023-08-16 20:53 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +
Лишние переносы строк в конце файла

2023-08-16 20:53 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    if (trainer.getNextQuestion() != null) {
Тут проблемка, ты два раза вызываешь getNextQuestion(), который по сути не просто возвращает тебе следующий вопрос, а создает новый и возвращает его. Вызывая два раза, ты пропускаешь вопросы.
Лучше использовать переменную и возможно стоит переименовать метод в `createAndGetNextQuestion()`

2023-08-16 20:53 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +    }    fun sendMenu(botToken: String, chatId: Int, ): String {
тут что то с форматированием

2023-08-16 20:53 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val sendQuestionBody = """
В итоге не валидный json получается.
Ниже по коду я добавил строку:
```Kotlin
println(sendQuestionBody)
```
и мне вывело:

```json
{
"chat_id": 28385144,
"text": "mouse",
"reply_markup": {
"inline_keyboard": [
            [
            {
                kotlin.Unit
            },
            {
                kotlin.Unit
            },
            {
                kotlin.Unit
            },
            {
                kotlin.Unit
            }
            ]
        ]
    }
}
```

а должно быть:

```json
{
{
    "chat_id": 28385144,
    "text": "mouse",
    "reply_markup": {
        "inline_keyboard": [
            [
                {
                    "text": "лошадь",
                    "callback_data": "answer_1"
                },
                {
                    "text": "мышь",
                    "callback_data": "answer_2"
                },
                {
                    "text": "мяч",
                    "callback_data": "answer_3"
                },
                {
                    "text": "привет",
                    "callback_data": "answer_4"
                }
            ]
        ]
    }
}

```

2023-08-17 08:52 UTC, MaxFix commented
но перестал работать sendMenu ((
дебажу, но пока не могу понять почему regex неверен

2023-08-17 13:04 UTC, MaxFix commented
Осталось брать только 4 варианта из списка
Тоесть если сейчас их больше, выводятся ВСЕ варианты

2023-08-17 18:54 UTC, danelyan requested changes
Отлично! Все работает ))

Есть пара моментов:
1) Если слова будут подлиннее, то на кнопках выстроенных в ряд не будут вмещаться слова. Давай разместим их в столбик
2) Сейчас у пользователя нет никакой возможности выйти из процесса изучения слов

2023-08-17 18:54 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        if (matchResultData != null && matchResultData.groupValues[1] == STATISTICS_TEXT.lowercase()) {
Почему тут не использовать data?

2023-08-17 18:54 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val urlSendMessage = "https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatId&text=$encoded"
1) Давай вынесем "https://api.telegram.org/bot" в константу, оно повторяется везде
2) botToken можно передавать параметром в конструктор TelegramBotService - ведь он не меняется по ходу работы программы

2023-08-18 05:09 UTC, danelyan approved these changes
Теперь идеально!
В следующем этапе все переделаем 😅

2023-08-18 08:00 UTC, merged